---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: another-client-one
  name: another-client-one
  namespace: dst-ns
spec:
  containers:
    - image: curlimages/curl:7.78.0
      name: client-one
      command:
        - sleep
        - "3600"
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  tolerations:
    - key: "node-role.kubernetes.io/infralayer"
      operator: "Exists"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: another-client-two
  name: another-client-two
  namespace: dst-ns
spec:
  containers:
    - image: curlimages/curl:7.78.0
      name: client-two
      command:
        - sleep
        - "3600"
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  tolerations:
    - key: "node-role.kubernetes.io/infralayer"
      operator: "Exists"
      effect: "NoSchedule"
